# The `_name` and `_value` will match the name and value properties of
# the suit's corresponding enum

[club]
_name = "CLUB"
_value = "club"
id = "C"
image = "♣"
colour = "black"

[diamond]
_name = "DIAMOND"
_value = "diamond"
id = "D"
image = "♦"
colour = "red"

[heart]
_name = "HEART"
_value = "heart"
id = "H"
image = "♥"
colour = "red"

[spade]
_name = "SPADE"
_value = "spade"
id = "S"
image = "♠"
colour = "black"
